# Generated by Django 4.1.7 on 2023-03-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post_curso',
        ),
    ]
