# Generated by Django 4.1.7 on 2023-03-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_buscar_post_estudiante_post_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buscar',
        ),
    ]
